### ISSUE TITLE
MISSING_DIGIT_AFTER_DOT_JSON_FILE

### ISSUE THREAD

**Issue by zerothi** [henu/bigjson#22]
I have a file created by a 3rd party user who consistently creates some values as `100.` or the likes of it.

Why is `bigjson` having a limitation about interpreting this as a number?
You even have a test to assert that `bigjson` catches:
```
{ "field": 100.}
```
Why not just assume this is `float(100.)`?

**Comment by henu** [comment]
Hi Zerothi!

`100.` is not valid JSON, and thus it is a *good* thing it raises exception. You can test this by yourself by entering the JSON to any JSON validator, for example this one: https://codebeautify.org/jsonvalidator/y23b12251

Although it might be tempting to allow non valid JSON in such "easy" cases, it is still good idea to follow the standard strictly. Otherwise you and other people might run in to problems if you ever decide to switch to another library.

**Comment by zerothi** [comment]
I see!! Thanks a lot, I can see that my inquiry was wrong! :)

Would you welcome a PR that explicitly states that this is standard compliant (ps another link of description: https://www.json.org/json-en.html)
